# This is a basic workflow that is manually triggered

name: mssqlsuite

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push]

jobs:
  test-everywhere:
    name: MSSQLSUITE
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run the action
        uses: potatoqualitee/mssqlsuite@v1.5.1
        with:
          install: sqlengine, sqlpackage
          show-log: true

      - name: Run sqlclient
        run: sqlcmd -S localhost -U sa -P dbatools.I0 -d tempdb -Q "SELECT @@version;"
      - name: Populate Test Data
        run: sqlcmd -S localhost -U sa -P dbatools.I0 -d test_database -Q "use test_database; CREATE TABLE Persons (PersonID int,Username varchar(255)); INSERT INTO Persons (PersonID, Username) VALUES (1, 'Test_Username'); SELECT * FROM Persons"